# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miuicamera-mondrian/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),miuicamera-mondrian)

endif
